Add config.useCropFirst
congnd/FMPhotoPicker pull request #53
Opened 2020-09-26 03:23 UTC by iBinh

Added a new config `useCropFirst` property that allows users to choose Crop or Filter will be displayed first in `FMImageEditorViewController`

2020-09-26 06:46 UTC, congnd commented
Seems no problem to me. But it seems that you are not updating the document in README file, can you consider to add a desscriotion for the newly added config?

2020-09-26 07:09 UTC, congnd requested changes

2020-09-26 07:09 UTC, congnd commented on README.md
> +An option that indicates which Crop or Filter view should be displayed first in `FMImageEditorViewController`.
> An option that indicates which Crop or Filter view should be displayed first in `FMImageEditorViewController`.

Should be: An option that indicates whether the crop menu should be selected by default in the `FMImageEditorViewController`.

2020-09-26 07:10 UTC, congnd commented
And please squash your commits.

2020-09-26 07:14 UTC, iBinh commented
Sorry, just updated

2020-09-26 07:54 UTC, congnd commented
> And please squash your commits.

@iBinh 
Could you please do this?

2020-09-26 16:49 UTC, iBinh commented
Yes, just squashed

2020-09-27 01:19 UTC, congnd commented
@iBinh 
Thanks for your contribution.

2020-09-27 01:19 UTC, congnd approved these changes

2020-09-27 01:20 UTC, merged